name: Docker Image CI for GHCR

on:
  push:

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build the package (no tests)
        run: mvn --batch-mode -DskipTests package

      - name: Run the unit tests
        run: mvn --batch-mode -Dmaven.test.failure.ignore=true test

      - name: Report test results
        if: always()
        uses: dorny/test-reporter@v1
        with:
          name: Maven Tests
          path: target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: true

      - name: Build and push the image
        run: |
          docker login --username marior17 --password ${{secrets.ACCESS_TOKEN}} ghcr.io
          docker build -t ghcr.io/marior17/arithmetic-service:latest --file Dockerfile .
          docker push ghcr.io/marior17/arithmetic-service:latest

      - name: Publish the image to azure container registry
        run: |
          docker login --username practicum7cr --password ${{secrets.AZURE_CONTAINER_REGISTRY}} practicum7cr.azurecr.io
          docker tag ghcr.io/marior17/arithmetic-service:latest practicum7cr.azurecr.io/arithmetic-service:latest
          docker push practicum7cr.azurecr.io/arithmetic-service:latest
